scala_library(
  dependencies=[
    '3rdparty/jvm:ammonite-ops',
    '3rdparty/jvm:ensime-api',
    '3rdparty/jvm:spray-json',
  ],
)

jvm_binary(
  name='ensime-gen',
  dependencies=[
    ':ensime',
  ],
)
