custom_scrooge_java_thrift_library(
  name='notifications',
  sources=['notifications.thrift'],
)

custom_scrooge_java_thrift_library(
  name='pingpong',
  sources=['pingpong.thrift'],
)

custom_scrooge_java_thrift_library(
  name='repo_backend',
  sources=['repo_backend.thrift'],
)

custom_scrooge_java_thrift_library(
  name='review_backend',
  sources=['review_backend.thrift'],
)

custom_scrooge_java_thrift_library(
  name='user',
  sources=['user.thrift'],
)
